# What is numpy?

#NumPy is a Python library used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices.
#NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
#NumPy stands for Numerical Python.



# why we use numpy?

#In Python we have lists that serve the purpose of arrays, but they are slow to process.
#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
#The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy
#Arrays are very frequently used in data science, where speed and resources are very important.
#Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

# Why is NumPy Faster Than Lists?

#NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently
#This behavior is called locality of reference in computer science.
#This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

# Which Language is NumPy written in?

#NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



In [4]:
#import NumPy
import numpy as np

In [5]:
#numpy :  single dimensional array means 1 D array use np.array([])
#we create a single dimensional array 
#numpy array means aollection of similar type of data 
#in 1D array have many record with the one column
A=np.array([67,89,90,56,76,54,98,79,48])

In [6]:
#print the data
print(A)

[67 89 90 56 76 54 98 79 48]


In [7]:
#Access value at 4th index
A[4]

76

In [8]:
#Access value from 3rd index to 6th index one by one then use slicing :
A[3:7] #here start=3rd index and stop=7-1=6th index and step=+1

array([56, 76, 54, 98])

# Property of 1D array

In [ ]:
#property of 1D array 
#1. dtype : to show datatype of numpy array A
#2. shaoe : to show How many rows and columns
#3. size :  to show no. of elements in 1D array
#itemsize : to show how much occupy memory by each elements of array
#nbytes : to show total memory occupiesd by Array A in RAM

In [9]:
#show the data type
A.dtype

dtype('int32')

In [10]:
##(9,)means 9 records and 1 columns
A.shape

(9,)

In [12]:
#1 byte=8 bits  bits means 0 & 1
#int : each int element occupy  4 bytes memory in ram means 4*8=32 bits
A.itemsize

4

In [13]:
#nbytes means no. of bytes
A.nbytes  

36

In [14]:
# To show Which type of VAriable A  ndarray means no. of dimension
type(A)

numpy.ndarray

In [15]:
# how much dimesion array coloumn 9 and row 1 i.e 1 daimention array(ndarray)
A.ndim 

1

In [16]:
 #int cannot accept  float but float  acacpt int that means int all value change in float,bydefault it take float value
A=np.array([45,67,89.98,45,78])

In [17]:
print(A)

[45.   67.   89.98 45.   78.  ]


In [18]:
A.dtype

dtype('float64')

In [19]:
A.itemsize

8

In [20]:
A.nbytes

40

In [21]:
A=np.array([34,67,89.76,43,82],int) 
#forcefully : int (means truncate after decimal)

In [22]:
print(A)

[34 67 89 43 82]


In [23]:
A.dtype

dtype('int32')

# Zeros array : -

In [24]:
#Zeros array : -
X=np.zeros(8) #here 8 means no. of elements=8 in array  by default type float
print(X)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
print(A) #change all value in int truncate means that

[34 67 89 43 82]


In [26]:
#Replace value at 2nd index with 67
X[2]=67
print(X)
X[0]=87.5
print(X)

[ 0.  0. 67.  0.  0.  0.  0.  0.]
[87.5  0.  67.   0.   0.   0.   0.   0. ]


In [27]:
X=np.zeros(8,int)# creat zero array withot float coz by defaualt it take float value 

In [28]:
print(X)

[0 0 0 0 0 0 0 0]


In [29]:
X[2]=87.8# to insert any value to any indext i.e 2 index value is 87.8

In [30]:
print(X)

[ 0  0 87  0  0  0  0  0]


In [31]:
A=np.ones(10)

In [32]:
print(A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [33]:
A.nbytes

80

In [34]:
#Mathmatical operations in 1D array 
A=np.array([34,67,89.76,43,82])
print(A)
#Sum of elements of 1D array A
A.sum()
#Average (mean) of element in 1D array A
A.mean() #mean=sum of elements of array A/no. of element of array A

[34.   67.   89.76 43.   82.  ]


63.152

In [35]:
A.max() #find max

89.76

# ********************************************2D ARRAY***********************************************************

#2D array means Two dimensional Array means many rows means meany records,
#and in each row,many columns  means to store data in tabular form
#numpy : 2D array create then use [[]]

In [36]:
#'''
#Python   R   ML
# 23      32  43
 #54      89  65
# 67      87  90
# 78     38  57

In [37]:
#create 2D array
A=np.array([[23,32,43],[54,89,65],[67,87,90],[78,38,57]])

In [38]:
print(A)

[[23 32 43]
 [54 89 65]
 [67 87 90]
 [78 38 57]]


In [39]:
#to show no. of dimension
A.ndim

2

In [40]:
A.size#to show number of element in A matrix

12

In [41]:
A.itemsize# to show byte of each element

4

In [42]:
print(A[1,])# to show row value 

[54 89 65]


In [43]:
#To show marks of all subjects of 1st index (row)
#A[rowindex,colindex]
print(A[2, 1])

87


In [ ]:
#Access 1st column(1st index) of all student (row)  use slicing 
#A[allrows,colstart:colstop] A[start index of row :stop index of row ,colindex]

In [44]:
print(A[:,1])

[32 89 87 38]


In [45]:
print(A[:,-1])  #access all rows of last column

[43 65 90 57]


In [46]:
print(A[1:4,:3])  #here row index start=1 and stop=4-1=3 and col start=0 
#and stop=3-1=2 means to show 0th col , 1st col and 2nd col of 1st,2nd and 3rd 
#row index

[[54 89 65]
 [67 87 90]
 [78 38 57]]


In [47]:
#sum of all elements of 2D array A
A.sum()

723

In [48]:
#sum of all elements of 2D array A
A.sum()

723

In [49]:
A.sum(axis=1)# row wise sum left to right 

array([ 98, 208, 244, 173])

In [50]:
A.sum(axis=0)#colwise show record top to bottom

array([222, 246, 255])

In [51]:
#Find average of all elements in array means find mean
A.mean()

60.25

In [52]:
#Rowwise mean of elements in array A
print(A.mean(axis=1))

[32.66666667 69.33333333 81.33333333 57.66666667]


In [53]:
#Columnwise mean of elements in array A
print(A.mean(axis=0))

[55.5  61.5  63.75]


# Transpose of Matrix

In [54]:
#Find the transpose of Matrix A then use transpose() inbuilt function
#transpose means interchange row and columns
print(A.transpose())

[[23 54 67 78]
 [32 89 87 38]
 [43 65 90 57]]


In [55]:
##use flatten() ==>Its convert two dimensional array to single dimensional array
print(A.flatten())

[23 32 43 54 89 65 67 87 90 78 38 57]


In [56]:
#zeros array in 2D Array
X=np.zeros((4,3)) #here 4 no. of rows and 3 no. of columns bydefault type float
print(X)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [57]:
#zeros array in 2D Array
X=np.zeros((4,3),int) #here 4 no. of rows and 3 no. of columns if u want int value 
print(X)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [58]:
X[1,2]=88 #replace the value of 0 with 88 in 1st row index and 2nd col index

In [59]:
print(X)

[[ 0  0  0]
 [ 0  0 88]
 [ 0  0  0]
 [ 0  0  0]]


# Identity matrix

In [60]:
#create Identity matrix 2*2 then use inbuilt fucntion of numpy ==>eye()
I=np.eye(2) #2 means 2 rows and 2 cols  and bydefault datatype =float
print(I)

[[1. 0.]
 [0. 1.]]


In [62]:
#another method to create a Single Dimensional Array (1 D) : arange() inbuilt
#method
A=np.arange(20) #here start=2 and stop=21 means 21-1=20 and step =+1 
#(because not mension)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [63]:
B=np.arange(2,21)#step=+2
print(B)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [64]:
C=np.arange(2,21,2)#step=+2
print(C)

[ 2  4  6  8 10 12 14 16 18 20]


In [65]:
#To create  a twodimensional array of 2*5
A=np.arange(10,20).reshape(2,5)
print(A)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [66]:
#To change 1D array to 2 D array of A array then use reshape() inbuilt function
#no. of rows=5 and no.of cols=2 means 5*2=10
B=A.reshape(5,2)
print(A)

[[10 11 12 13 14]
 [15 16 17 18 19]]


# BROADCASTING IN NumPy 

In [67]:
#for eg. 2D array A

In [68]:
A=np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400]])

In [69]:
print(A)

[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]


In [70]:
#create B array
B=np.array([[5,6,7,8]])

In [71]:
A+B

array([[  6,   8,  10,  12],
       [ 15,  26,  37,  48],
       [105, 206, 307, 408]])

# Scaler Vector

In [72]:
import numpy as np


In [73]:
#scalar vector
B=5

In [74]:
A=np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400]])

In [75]:
A+B

array([[  6,   7,   8,   9],
       [ 15,  25,  35,  45],
       [105, 205, 305, 405]])

In [76]:
import numpy as np
#BoardCasting in numpy
#create 2D Array  A 4*3
A=np.array([[10,20,30],[1,2,3],[5,6,7],[20,30,40]])
#create  2D array B 1*3
B=np.array([5,7,9])
print(A)

[[10 20 30]
 [ 1  2  3]
 [ 5  6  7]
 [20 30 40]]


In [77]:
print(B)

[5 7 9]


In [78]:
A+B

array([[15, 27, 39],
       [ 6,  9, 12],
       [10, 13, 16],
       [25, 37, 49]])

# VECTORISATION 

In [79]:
#VECTORISATION :  to apply any mathamatical operation on 2D array 
#means to add/sub/mul/div of constant value in 2D array

In [80]:
import numpy as np
#BoardCasting in numpy
#create 2D Array  A 4*3
A=np.array([[10,20,30],[1,2,3],[5,6,7],[20,30,40]])
#create  2D array B 1*3
B=np.array([5,7,9])
print(A)


[[10 20 30]
 [ 1  2  3]
 [ 5  6  7]
 [20 30 40]]


In [81]:
print(B)
A+B

[5 7 9]


array([[15, 27, 39],
       [ 6,  9, 12],
       [10, 13, 16],
       [25, 37, 49]])

In [82]:
#Cross product of matrix(*) and dot product of matrix(.)
#product means multiplication

In [85]:
#suppose Crprint(B)eate Matrix A and B both are 2*2
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [86]:
print(A)

[[1 2]
 [3 4]]


In [87]:
print(B)

[[5 6]
 [7 8]]


#Cross product *

In [88]:
#Cross product *
C=A*B
print(C)

[[ 5 12]
 [21 32]]


#Dot product

In [90]:
#Dot product then use inbuilt function dot(.) is defined in numpy array
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [91]:
#concatenate() means to join 2 or more array
#apple 1D array
A=np.array([23,56,78])

In [92]:
print(A)

[23 56 78]


In [93]:
B=np.array([23,76,89])

In [94]:
print(B)

[23 76 89]


In [95]:
C=np.array([7,8,9,10,11])

#concatenate

In [96]:
#concate A,B and C array and hold in new array D
D=np.concatenate((A,B,C))

In [97]:
print(D)

[23 56 78 23 76 89  7  8  9 10 11]


In [98]:
#suppose Create Matrix A and B both are 2*2
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [99]:
#Concate of matrix A and B (2D array)
np.concatenate((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
#concate of matrix A and B (2D array)
np.concatenate((A,B),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [101]:
import numpy as np

In [102]:
print("version: ",np.__version__)#Print the numpy version and the configuration

version:  1.18.1


In [103]:
print('bytes: ',A.size*A.itemsize) #How to find the memory size of any array?

bytes:  16


In [104]:
#documentation of the numpy add function from the command line

print('python import numpy; numpy.info(numpy.add)')
                            

python import numpy; numpy.info(numpy.add)
